# Mark Distribution

1. Attendance - 03
2. Assignment - 07
3. Lab Viva - 03
4. Lab Final - 07

import numpy as np

In [ ]:
import numpy as np

In [ ]:
list = [1,2,2,34,5,6,7,6]
arr = np.array([1,2,33,4,5,6,67])

1. numpy initialization
[0,0,0,0,0,0]
2. arr = [0]*capacity
3. arr = np.array([0]*capacity)
4. Build in numpy function
arr =  np.zeros(capacity,floating data type by default)
5. arr =  np.zeros(capacity,dtype = int )
6. 2D array :
2D_arr = np.zeros((row,col))
7. iretaring numpy :
for i in range(start,len(arr),1)
backward irtertion ;
for i in range(len(arr)-1,-1,-1)
8. Slicing

1. Append in numpy
arr = np.array([2,3,3,4,5])
2. single value np.append(arr,elem)
3. muiltiple value np.append(arr,[elem])
4. np.prod(arr)

In [ ]:
arr = np.array([2,3,3,4,5])

In [ ]:
np.prod(arr)

360

In [ ]:
np.sum(arr)

17

In [ ]:
np.append(arr,56)

array([ 2,  3,  3,  4,  5, 56])

# Visualization

In [ ]:
import numpy as np

# Corrected array creation
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Display the created array
print("2D Array:")
print(arr)


2D Array:
[[1 2 3]
 [4 5 6]]


# r,c = arr.shape

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array (number of rows, number of columns)
r, c = arr.shape

# Display the shape
print("Number of rows:", r)
print("Number of columns:", c)


Number of rows: 2
Number of columns: 3


In [ ]:
np.sum(arr)

21

In [ ]:
np.sum(arr,axis=0)

array([5, 7, 9])

 # axis = 0 , Vertical Sum Or Column sum

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15])

 # axis = 1 , Horizontal Sum Or Row sum

In [ ]:
r,c = arr.shape

In [ ]:
np.linspace(1,100,50)

# it will generate 50 points where 50 eqally spaced

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

exponent ** supports numpy

In [ ]:
a = np.array([2,3,4])**2
print(a)

[ 4  9 16]


In [ ]:
np.array([2,3,4])**2

array([ 4,  9, 16])

row .... arr[0] Or arr[0:2,:]
column .... arr[:,0]

 arr[0:2,:]

 arr[0:2,:]

 1. first portion decides row
 2. second portion decides colum
 3. the above value will print 2 rows and all elems of columns

In [ ]:
co_eff = [2,1,4,3]
sum = 0
for i in range(len(co_eff)) :
  sum =
  print(co_eff[i])


2
1
4
3


In [ ]:
co_eff = [2,1,4,3]
li = []
p = [6,7,8]
j = 0
while j < len(p) :
  sum = 0
  for i in range(len(co_eff)) :
    sum += co_eff[i]*p[j]**i
    # print(co_eff[i])
    li.append(sum)
    # i+= 1
  j+=1
print(li)

[2, 8, 152, 800, 2, 9, 205, 1234, 2, 10, 266, 1802]


In [ ]:
co_eff = [2,1,4,3]
li = []
p = num[6,7,8]

for j in range(len(p)):
  sum = 0
  for i in range(len(co_eff)) :
    sum += co_eff[i]*p[j]**i
    # print(co_eff[i])
  li.append(sum)

print(li)